<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-B2220QC" ignored="0" name="Default test" tests="1" failures="1" timestamp="2021-06-07T20:05:49 IST" time="14.795" errors="0">
  <testcase name="@AfterMethod AfterMethod" time="3.007" classname="pom.classes.TestClass1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at pom.classes.TestClass1.AfterMethod(TestClass1.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod AfterMethod -->
  <testcase name="@AfterClass AfterClass" time="-1.623076549516E9" classname="pom.classes.TestClass1">
    <skipped/>
  </testcase> <!-- @AfterClass AfterClass -->
  <testcase name="verifyTaskLink" time="0.013" classname="pom.classes.TestClass1">
    <failure type="java.lang.Error" message="Unresolved compilation problems: 
	Constructor call must be the first statement in a constructor
	Syntax error on token &amp;quot;.&amp;quot;, super expected after this token
	condition cannot be resolved to a variable
	condition cannot be resolved to a variable
	Syntax error on token &amp;quot;)&amp;quot;, @ expected
	Syntax error, type annotations are illegal here
	Syntax error on token &amp;quot;)&amp;quot;, @ expected
	Syntax error, type annotations are illegal here
	The method fail() is undefined for the type TestClass1
	Syntax error, insert &amp;quot;)&amp;quot; to complete MethodInvocation
	Syntax error, insert &amp;quot;)&amp;quot; to complete MethodInvocation
	Syntax error, insert &amp;quot;;&amp;quot; to complete Statement
	The method assertAll() is undefined for the type TestClass1
	Syntax error, insert &amp;quot;;&amp;quot; to complete Statement
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
Constructor call must be the first statement in a constructor
Syntax error on token ".", super expected after this token
condition cannot be resolved to a variable
condition cannot be resolved to a variable
Syntax error on token ")", @ expected
Syntax error, type annotations are illegal here
Syntax error on token ")", @ expected
Syntax error, type annotations are illegal here
The method fail() is undefined for the type TestClass1
Syntax error, insert ")" to complete MethodInvocation
Syntax error, insert ")" to complete MethodInvocation
Syntax error, insert ";" to complete Statement
The method assertAll() is undefined for the type TestClass1
Syntax error, insert ";" to complete Statement

at pom.classes.TestClass1.verifyTaskLink(TestClass1.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyTaskLink -->
</testsuite> <!-- Default test -->
